f = @(u,y) (W_training_D(1)+W_training_D(5)+W_training_D(9))*u +... 
    (W_training_D(2)+W_training_D(6)+W_training_D(10))*u.^2 +...
    (W_training_D(3)+W_training_D(7)+W_training_D(11))*u.^3 +...
    (W_training_D(4)+W_training_D(8)+W_training_D(12))*u.^4 +...
    (W_training_D(13)+W_training_D(17)+W_training_D(21)-1)*y +... 
    (W_training_D(14)+W_training_D(18)+W_training_D(22))*y.^2 +... 
    (W_training_D(15)+W_training_D(19)+W_training_D(23))*y.^3 +...
    (W_training_D(16)+W_training_D(20)+W_training_D(24))*y.^4;

G = linspace(-1,1.5, 1000).';
for i=1:numel(G)
sol = fsolve(@(y)f(G(i),y),[1,1]);
x(i,:) = sol;
end 

plot(G,x(:,1))


xlabel('u');
ylabel('y');
title('charakterystyka statyczna y(u)');